### ISSUE TITLE
[Online Multiplayer] Make a subtle animation when copying the Peer ID

### ISSUE THREAD

**Issue by iByteABit256** [iByteABit256/tic-tac-toes#21]
Right now when you click the Peer ID, it is silently copied to the clipboard. It would be nice if it did a subtle animation with CSS to indicate that is has been copied.

**Comment by DanejSakshi13** [comment]
Hi there! I've reviewed the issue regarding the need to add an animation when copying the Peer ID. I'm confident that I can implement the required changes to address this issue effectively. Could you please assign this task to me? I'm eager to start working on it and provide a solution promptly. 
Thank you!

**Comment by iByteABit256** [comment]
Yes of course!
